name: active_dart
version: 1.1.0
description: >-
  Helpful Ruby-on-Rails style helpers to make the code readable.
homepage: https://github.com/robturtle/active_dart
documentation: https://github.com/robturtle/active_dart
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
dev_dependencies:
  test: '>=1.15.0 <2.0.0'